---
- name: use apache_vhost role playbook
  hosts: node2
  become: true

  pre_tasks:
    - ansible.builtin.debug:
        msg: 'Beginning web server configuration.'

  roles:
    - apache_vhost

  post_tasks:
    - ansible.builtin.debug:
        msg: 'Web server has been configured.'
